/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author NIKO
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_rut = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_apellidop = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_apellidom = new javax.swing.JTextField();
        rb_masculino = new javax.swing.JRadioButton();
        rb_femenino = new javax.swing.JRadioButton();
        btn_ingresar_alumno = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rb_mañana = new javax.swing.JRadioButton();
        rb_tarde = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_apellidoprof = new javax.swing.JTextField();
        txt_rutprof = new javax.swing.JTextField();
        txt_nomprof = new javax.swing.JTextField();
        rb_mascprof = new javax.swing.JRadioButton();
        rb_femprof = new javax.swing.JRadioButton();
        cb_leng = new javax.swing.JCheckBox();
        cb_mat = new javax.swing.JCheckBox();
        cb_hist = new javax.swing.JCheckBox();
        cb_cie = new javax.swing.JCheckBox();
        cb_ing = new javax.swing.JCheckBox();
        cb_fis = new javax.swing.JCheckBox();
        btn_ingresar_profesor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_profrut = new javax.swing.JTextField();
        txt_alumrut = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        rb_fisica = new javax.swing.JRadioButton();
        rb_lenguaje = new javax.swing.JRadioButton();
        rb_matematicas = new javax.swing.JRadioButton();
        rb_historia = new javax.swing.JRadioButton();
        rb_ciencias = new javax.swing.JRadioButton();
        rb_ingles = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_acum4 = new javax.swing.JTextField();
        txt_nota1 = new javax.swing.JTextField();
        txt_nota2 = new javax.swing.JTextField();
        txt_nota3 = new javax.swing.JTextField();
        txt_nota4 = new javax.swing.JTextField();
        txt_acum1 = new javax.swing.JTextField();
        txt_acum2 = new javax.swing.JTextField();
        txt_acum3 = new javax.swing.JTextField();
        btn_ingresar_notas = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        txt_asig_cod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt_nom_prof = new javax.swing.JTextField();
        txt_cod_asignatura = new javax.swing.JTextField();
        txt_nom_asig = new javax.swing.JTextField();
        rb_8hrs = new javax.swing.JRadioButton();
        rb_2hrs = new javax.swing.JRadioButton();
        rb_4hrs = new javax.swing.JRadioButton();
        btn_ingrear_asignatura = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RUT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 30, 20));
        jPanel1.add(txt_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 80, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMBRE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 80, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("APELLIDO P.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel1.add(txt_apellidop, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 80, -1));

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("APELLIDO M.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("SEXO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));
        jPanel1.add(txt_apellidom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 80, -1));

        rb_masculino.setText("MASCULINO");
        jPanel1.add(rb_masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 33, 90, 20));

        rb_femenino.setText("FEMENINO");
        jPanel1.add(rb_femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 90, -1));

        btn_ingresar_alumno.setText("INGRESAR");
        jPanel1.add(btn_ingresar_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, 40));

        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("JORNADA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        rb_mañana.setText("MAÑANA");
        jPanel1.add(rb_mañana, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        rb_tarde.setText("TARDE");
        jPanel1.add(rb_tarde, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 70, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 435));

        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jTabbedPane2.addTab("Alumno", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("RUT");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 30, 20));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NOMBRE");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("APELLIDO ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("SEXO");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("ASIGNATURAS");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        txt_apellidoprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoprofActionPerformed(evt);
            }
        });
        jPanel2.add(txt_apellidoprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 70, -1));
        jPanel2.add(txt_rutprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 70, -1));
        jPanel2.add(txt_nomprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 70, -1));

        rb_mascprof.setText("MASCULINO");
        jPanel2.add(rb_mascprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 90, -1));

        rb_femprof.setText("FEMENINO");
        rb_femprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_femprofActionPerformed(evt);
            }
        });
        jPanel2.add(rb_femprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 90, -1));

        cb_leng.setText("LENGUAJE");
        jPanel2.add(cb_leng, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 100, -1));

        cb_mat.setText("MATEMATICAS");
        jPanel2.add(cb_mat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        cb_hist.setText("HISTORIA");
        jPanel2.add(cb_hist, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 100, -1));

        cb_cie.setText("CIENCIAS");
        jPanel2.add(cb_cie, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 100, -1));

        cb_ing.setText("INGLES");
        jPanel2.add(cb_ing, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 100, -1));

        cb_fis.setText("ED. FISICA");
        jPanel2.add(cb_fis, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 100, -1));

        btn_ingresar_profesor.setText("INGRESAR");
        jPanel2.add(btn_ingresar_profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 323, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 416));

        jTabbedPane2.addTab("Profesor", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("RUT DEL ALUMNO");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, 20));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("RUT DEL PROFESOR");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));
        jPanel3.add(txt_profrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 90, -1));
        jPanel3.add(txt_alumrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, -1));

        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("ASIGNATURA");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        rb_fisica.setText("ED. FISICA");
        jPanel3.add(rb_fisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 110, -1));

        rb_lenguaje.setText("LENGUAJE");
        jPanel3.add(rb_lenguaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 110, -1));

        rb_matematicas.setText("MATEMATICAS");
        jPanel3.add(rb_matematicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 110, -1));

        rb_historia.setText("HISTORIA");
        jPanel3.add(rb_historia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, -1));

        rb_ciencias.setText("CIENCIAS");
        jPanel3.add(rb_ciencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, -1));

        rb_ingles.setText("INGLES");
        rb_ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_inglesActionPerformed(evt);
            }
        });
        jPanel3.add(rb_ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 110, -1));

        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("ACUMULATIVA 4");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("NOTA 1");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("NOTA 2");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel22.setForeground(new java.awt.Color(240, 240, 240));
        jLabel22.setText("NOTA 3");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabel23.setForeground(new java.awt.Color(240, 240, 240));
        jLabel23.setText("NOTA 4");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel24.setForeground(new java.awt.Color(240, 240, 240));
        jLabel24.setText("ACUMULATIVA 1");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel25.setForeground(new java.awt.Color(240, 240, 240));
        jLabel25.setText("ACUMULATIVA 2");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jLabel26.setForeground(new java.awt.Color(240, 240, 240));
        jLabel26.setText("ACUMULATIVA 3");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));
        jPanel3.add(txt_acum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 60, -1));
        jPanel3.add(txt_nota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 60, -1));
        jPanel3.add(txt_nota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 60, -1));

        txt_nota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nota3ActionPerformed(evt);
            }
        });
        jPanel3.add(txt_nota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 60, -1));
        jPanel3.add(txt_nota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 60, -1));
        jPanel3.add(txt_acum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 60, -1));
        jPanel3.add(txt_acum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 60, -1));
        jPanel3.add(txt_acum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 60, -1));

        btn_ingresar_notas.setText("INGRESAR");
        jPanel3.add(btn_ingresar_notas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 313, -1, 50));

        jLabel27.setForeground(new java.awt.Color(240, 240, 240));
        jLabel27.setText("COD DE ASIGNATURA");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel3.add(txt_asig_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 60, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 456, 426));

        jTabbedPane2.addTab("Notas", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setForeground(new java.awt.Color(240, 240, 240));
        jLabel29.setText("COD DE ASIGNATURA");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel30.setForeground(new java.awt.Color(240, 240, 240));
        jLabel30.setText("NOMBRE");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel31.setForeground(new java.awt.Color(240, 240, 240));
        jLabel31.setText("HORAS SEMANALES");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel32.setForeground(new java.awt.Color(240, 240, 240));
        jLabel32.setText("PROFESOR QUE LA IMPARTE");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel4.add(txt_nom_prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 100, -1));
        jPanel4.add(txt_cod_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 100, 20));
        jPanel4.add(txt_nom_asig, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, -1));

        rb_8hrs.setText("8 HRS");
        jPanel4.add(rb_8hrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        rb_2hrs.setText("2 HRS");
        jPanel4.add(rb_2hrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        rb_4hrs.setText("4 HRS");
        jPanel4.add(rb_4hrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        btn_ingrear_asignatura.setText("ingresar");
        jPanel4.add(btn_ingrear_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 303, 100, 50));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 456, 435));

        jTabbedPane2.addTab("Asignaturas", jPanel4);

        jPanel5.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 440));

        jTabbedPane1.addTab("Insertar", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Actualizar", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Mostrar", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Eliminar", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_apellidoprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoprofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoprofActionPerformed

    private void rb_femprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_femprofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_femprofActionPerformed

    private void rb_inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_inglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_inglesActionPerformed

    private void txt_nota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nota3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingrear_asignatura;
    private javax.swing.JButton btn_ingresar_alumno;
    private javax.swing.JButton btn_ingresar_notas;
    private javax.swing.JButton btn_ingresar_profesor;
    private javax.swing.JCheckBox cb_cie;
    private javax.swing.JCheckBox cb_fis;
    private javax.swing.JCheckBox cb_hist;
    private javax.swing.JCheckBox cb_ing;
    private javax.swing.JCheckBox cb_leng;
    private javax.swing.JCheckBox cb_mat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton rb_2hrs;
    private javax.swing.JRadioButton rb_4hrs;
    private javax.swing.JRadioButton rb_8hrs;
    private javax.swing.JRadioButton rb_ciencias;
    private javax.swing.JRadioButton rb_femenino;
    private javax.swing.JRadioButton rb_femprof;
    private javax.swing.JRadioButton rb_fisica;
    private javax.swing.JRadioButton rb_historia;
    private javax.swing.JRadioButton rb_ingles;
    private javax.swing.JRadioButton rb_lenguaje;
    private javax.swing.JRadioButton rb_mascprof;
    private javax.swing.JRadioButton rb_masculino;
    private javax.swing.JRadioButton rb_matematicas;
    private javax.swing.JRadioButton rb_mañana;
    private javax.swing.JRadioButton rb_tarde;
    private javax.swing.JTextField txt_acum1;
    private javax.swing.JTextField txt_acum2;
    private javax.swing.JTextField txt_acum3;
    private javax.swing.JTextField txt_acum4;
    private javax.swing.JTextField txt_alumrut;
    private javax.swing.JTextField txt_apellidom;
    private javax.swing.JTextField txt_apellidop;
    private javax.swing.JTextField txt_apellidoprof;
    private javax.swing.JTextField txt_asig_cod;
    private javax.swing.JTextField txt_cod_asignatura;
    private javax.swing.JTextField txt_nom_asig;
    private javax.swing.JTextField txt_nom_prof;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nomprof;
    private javax.swing.JTextField txt_nota1;
    private javax.swing.JTextField txt_nota2;
    private javax.swing.JTextField txt_nota3;
    private javax.swing.JTextField txt_nota4;
    private javax.swing.JTextField txt_profrut;
    private javax.swing.JTextField txt_rut;
    private javax.swing.JTextField txt_rutprof;
    // End of variables declaration//GEN-END:variables
}
